### ISSUE TITLE
memory utilization error

### ISSUE THREAD

**Issue by benjaminBrownlee** [alphasp/pxview#64]
When I try to use this app, I constantly run into memory errors (see error log below). This occurs even if it is the only app I have open, and can happen after just a couple minutes of swiping left through the illustrations in my recommended feed. What sort of memory resources are expected to use this app, and how are they managed? Is this a memory leak, or does the app simply choose to keep past images and crash instead of freeing memory when needed? Its been a while since I have done mobile development (and I have never touched reactive native) but I'm willing to help.

```log
--------- beginning of crash
12-29 11:11:02.030  1802  2542 E AndroidRuntime: FATAL EXCEPTION: ServiceModule
12-29 11:11:02.030  1802  2542 E AndroidRuntime: Process: com.sec.imsservice, PID: 1802
12-29 11:11:02.030  1802  2542 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke vir
tual method 'boolean com.sec.internal.ims.options.CapabilityConfig.isDisableInitialScan()' on a null o
bject reference
12-29 11:11:02.030  1802  2542 E AndroidRuntime:        at com.sec.internal.ims.options.CapabilityDisc
overyModule.onUserSwitched(CapabilityDiscoveryModule.java:2411)
12-29 11:11:02.030  1802  2542 E AndroidRuntime:        at com.sec.internal.ims.options.CapabilityDisc
overyModule.handleMessage(CapabilityDiscoveryModule.java:806)
12-29 11:11:02.030  1802  2542 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.
java:102)
12-29 11:11:02.030  1802  2542 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
12-29 11:11:02.030  1802  2542 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.
java:61)
01-01 00:55:56.470 10111 10175 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-01 00:55:56.470 10111 10175 E AndroidRuntime: Process: com.utopia.pxview, PID: 10111
01-01 00:55:56.470 10111 10175 E AndroidRuntime: com.facebook.react.common.JavascriptException: Error:
 Out of memory, stack:
01-01 00:55:56.470 10111 10175 E AndroidRuntime: stringify@-1
01-01 00:55:56.470 10111 10175 E AndroidRuntime: E@1541:676
01-01 00:55:56.470 10111 10175 E AndroidRuntime: p@1541:581
01-01 00:55:56.470 10111 10175 E AndroidRuntime: y@134:580
01-01 00:55:56.470 10111 10175 E AndroidRuntime: callTimers@134:2629
01-01 00:55:56.470 10111 10175 E AndroidRuntime: value@41:3350
01-01 00:55:56.470 10111 10175 E AndroidRuntime: <unknown>@41:747
01-01 00:55:56.470 10111 10175 E AndroidRuntime: value@41:2610
01-01 00:55:56.470 10111 10175 E AndroidRuntime: value@41:719
01-01 00:55:56.470 10111 10175 E AndroidRuntime: value@-1
01-01 00:55:56.470 10111 10175 E AndroidRuntime: 
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsM
anagerModule.reportException(ExceptionsManagerModule.java:83)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Meth
od)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper
.invoke(JavaMethodWrapper.java:372)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
01-01 00:55:56.470 10111 10175 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:762)
```

**Comment by alphasp** [comment]
Could you share your device name and model?

**Comment by benjaminBrownlee** [comment]
device: Samsung SM-J320V (Android 7.1.1)
app: PxView 4.6

I do know I have an older device, but I others with newer devices have experienced laggy or unstable conditions in the app after browsing for longer periods of time or with greater depth (larger stack of views). These may both be related to memory management issues.
